/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./**/*.{js,ts,jsx,tsx,vue,svelte}", // Ajusta según el framework que uses (si aplica)
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2f2ebe",
        "error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "inverse-surface": "#dae2fd",
        "primary-fixed-dim": "#c0c1ff",
        "surface-tint": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#301400",
        "inverse-primary": "#494bd6",
        "on-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        background: "#0b1326",
        "on-tertiary-fixed-variant": "#703700",
        "outline-variant": "#464554",
        "surface-bright": "#31394d",
        "on-secondary-fixed-variant": "#39485a",
        "on-secondary-fixed": "#0d1c2d",
        "secondary-fixed": "#d4e4fa",
        "on-error-container": "#ffdad6",
        outline: "#908fa0",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20",
        tertiary: "#ffb783",
        error: "#ffb4ab",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary": "#233143",
        secondary: "#b9c8de",
        "surface-variant": "#2d3449",
        "on-primary": "#1000a9",
        "surface-container-low": "#131b2e",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary-container": "#a7b6cc",
        "on-primary-container": "#0d0096",
        "on-tertiary-container": "#452000",
        "on-tertiary": "#4f2500",
        "secondary-container": "#39485a",
        "tertiary-container": "#d97721",
        "primary-container": "#8083ff",
        "on-background": "#dae2fd",
        "surface-container-highest": "#2d3449",
        surface: "#0b1326",
        "surface-container": "#171f33",
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed-dim": "#b9c8de",
        primary: "#c0c1ff",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        unit: "4px",
        xs: "4px",
        margin: "32px",
        md: "16px",
        "2xl": "64px",
        lg: "24px",
        gutter: "24px",
        xl: "40px",
      },
      fontFamily: {
        h2: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        h2: ["30px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};